<?php
/* 企画・制作
*************************************************************************************/
$producer = array(
  array(
    'icon_path'=>'/images/member/icon/sinozakiserori.jpg',
    'name'=>'篠崎せろり',
    'role'=>'Producer',
    'twitter_url'=>'https://twitter.com/sinozakiserori',
    'link_url'=>''
  )
);

/* WEBデザイン
*************************************************************************************/
$web = array(
  array(
    'icon_path'=>'/images/member/icon/Waterfox_skjp.png',
    'name'=>'水狐',
    'role'=>'WEB Designer',
    'twitter_url'=>'https://twitter.com/Waterfox_skjp',
    'link_url'=>''
  )
);

/* アイコン・ロゴデザイン
*************************************************************************************/
$design = array(
  array(
    'icon_path'=>'',
    'name'=>'サイチ',
    'role'=>'Designer<br>No.4',
    'twitter_url'=>'',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/KarikariumeNo1.jpg',
    'name'=>'カリカリ梅',
    'role'=>'Designer<br>No.16',
    'twitter_url'=>'https://twitter.com/KarikariumeNo1',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/moaiguma.jpg',
    'name'=>'高嶺そら',
    'role'=>'Designer<br>No.61',
    'twitter_url'=>'https://twitter.com/moaiguma',
    'link_url'=>''
  )
);

/* 制作協力
*************************************************************************************/
$cooperator = array(
  array(
    'icon_path'=>'/images/member/icon/cherryfront.jpg',
    'name'=>'桜前線',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/cherryfront',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/nazonekodan.jpg',
    'name'=>'ナゾネコ団',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/nazonekodan',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/pleiadesplanet.jpg',
    'name'=>'プレアデスプラネッツ',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/pleiadesplanet',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Puzzle_Suddenly.jpg',
    'name'=>'突然の謎解き',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/Puzzle_Suddenly',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/queens1717.jpg',
    'name'=>'クイーンズ',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/queens1717',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/nazonoshi.jpg',
    'name'=>'なぞのし',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/nazonoshi',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/sodenasi0509.jpg',
    'name'=>'袖無',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/sodenasi0509',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/kokokoe321.jpg',
    'name'=>'ここあ',
    'role'=>'Cooperator',
    'twitter_url'=>'https://twitter.com/kokokoe321',
    'link_url'=>''
  )
);

/* 謎制作
*************************************************************************************/
$supporter = array(
  array(
    'icon_path'=>'/images/member/icon/KyuriMakiMaki.jpg',
    'name'=>'きゅうり巻き',
    'role'=>'No.1',
    'twitter_url'=>'https://twitter.com/KyuriMakiMaki',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/viola_reald1.png',
    'name'=>'VIOLA',
    'role'=>'No.2',
    'twitter_url'=>'https://twitter.com/viola_reald1',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/REWbyT.jpg',
    'name'=>'は',
    'role'=>'No.5',
    'twitter_url'=>'https://twitter.com/REWbyT',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/seaster1206.jpg',
    'name'=>'ちゃんにー',
    'role'=>'NO.7',
    'twitter_url'=>'https://twitter.com/seaster1206',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'',
    'name'=>'サニー',
    'role'=>'No.8',
    'twitter_url'=>'',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/___Mr_J___.jpg',
    'name'=>'田中太郎',
    'role'=>'No.9',
    'twitter_url'=>'https://twitter.com/___Mr_J___',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/naoki0420.jpg',
    'name'=>'直樹',
    'role'=>'No.10',
    'twitter_url'=>'https://twitter.com/naoki0420',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/harinedumi.jpg',
    'name'=>'はりねずみ',
    'role'=>'No.11',
    'twitter_url'=>'https://twitter.com/harinedumi',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/common179.jpg',
    'name'=>'Nam0Zan',
    'role'=>'No.12',
    'twitter_url'=>'https://twitter.com/common179',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/KJRY0.jpg',
    'name'=>'瓜良牙',
    'role'=>'No.13',
    'twitter_url'=>'https://twitter.com/KJRY0',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/rekihidan.jpg',
    'name'=>'想幻',
    'role'=>'No.14',
    'twitter_url'=>'https://twitter.com/rekihidan',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/chie2401.jpg',
    'name'=>'ちえ',
    'role'=>'No.17',
    'twitter_url'=>'https://twitter.com/chie2401',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/hagenyan0713.jpg',
    'name'=>'はG',
    'role'=>'No.18',
    'twitter_url'=>'https://twitter.com/hagenyan0713',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/_EURO_.jpg',
    'name'=>'ゆーろー',
    'role'=>'No.19',
    'twitter_url'=>'https://twitter.com/_EURO_',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/SweetFan_.jpg',
    'name'=>'甘い扇風機',
    'role'=>'No.20',
    'twitter_url'=>'https://twitter.com/SweetFan_',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/twiline_.jpg',
    'name'=>'そう',
    'role'=>'No.21',
    'twitter_url'=>'https://twitter.com/twiline_',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Magnet_Compass.jpg',
    'name'=>'MAGNET',
    'role'=>'No.22',
    'twitter_url'=>'https://twitter.com/Magnet_Compass',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/3337_46166.jpg',
    'name'=>'竜尺享尓',
    'role'=>'No.23',
    'twitter_url'=>'https://twitter.com/3337_46166',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Ch_North.jpg',
    'name'=>'C＆C',
    'role'=>'No.24',
    'twitter_url'=>'https://twitter.com/Ch_North',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/__Netu__.jpg',
    'name'=>'熱',
    'role'=>'No.25',
    'twitter_url'=>'https://twitter.com/__Netu__',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/nanajij.jpg',
    'name'=>'ヒラサワゆーたろー',
    'role'=>'No.26',
    'twitter_url'=>'https://twitter.com/nanajij',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Cltakenazosuki.png',
    'name'=>'たけたけ',
    'role'=>'No.27',
    'twitter_url'=>'https://twitter.com/CLtakenazosuki',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Kuruton_Naz0.jpg',
    'name'=>'Kuruton',
    'role'=>'No.28',
    'twitter_url'=>'https://twitter.com/Kuruton_Naz0',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/orikisiori.jpg',
    'name'=>'折木栞',
    'role'=>'No.29',
    'twitter_url'=>'https://twitter.com/orikisiori',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/naoperc.jpg',
    'name'=>'なお',
    'role'=>'No.30',
    'twitter_url'=>'https://twitter.com/naoperc',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/rokukan.png',
    'name'=>'ろくかん',
    'role'=>'No.31',
    'twitter_url'=>'https://twitter.com/rokukan',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Hiromi_g3331.jpg',
    'name'=>'ごうたそ',
    'role'=>'No.32',
    'twitter_url'=>'https://twitter.com/Hiromi_g3331',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'',
    'name'=>'ずやぁ',
    'role'=>'No.33',
    'twitter_url'=>'',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'',
    'name'=>'ふーか',
    'role'=>'No.34',
    'twitter_url'=>'',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/miyu55_ridd.jpg',
    'name'=>'にわ',
    'role'=>'No.35',
    'twitter_url'=>'https://twitter.com/miyu55_ridd',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/AirZoleBros.jpg',
    'name'=>'フスマ',
    'role'=>'No.36',
    'twitter_url'=>'https://twitter.com/AirZoleBros',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/serendattakamo.jpg',
    'name'=>'やだい',
    'role'=>'No.37',
    'twitter_url'=>'https://twitter.com/serendattakamo',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/tdphw945.jpg',
    'name'=>'千夢',
    'role'=>'No.38',
    'twitter_url'=>'https://twitter.com/tdphw945',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'',
    'name'=>'ヒロ',
    'role'=>'No.39',
    'twitter_url'=>'',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/860_no96.jpg',
    'name'=>'yuch',
    'role'=>'No.40',
    'twitter_url'=>'https://twitter.com/860_no96',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/t_t_p_p.jpg',
    'name'=>'iwahasu',
    'role'=>'No.41',
    'twitter_url'=>'https://twitter.com/t_t_p_p',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/xcirqu.jpg',
    'name'=>'xa',
    'role'=>'No.42',
    'twitter_url'=>'https://twitter.com/xcirqu',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/himajin_always.jpg',
    'name'=>'himajin0405',
    'role'=>'No.43',
    'twitter_url'=>'https://twitter.com/himajin_always',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/skyblueamity.jpg',
    'name'=>'ひゃん',
    'role'=>'No.44',
    'twitter_url'=>'https://twitter.com/skyblueamity',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/OjisanNu.png',
    'name'=>'桂木',
    'role'=>'No.45',
    'twitter_url'=>'https://twitter.com/OjisanNu',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Tamiya667.jpg',
    'name'=>'Tamiya黎明',
    'role'=>'No.46',
    'twitter_url'=>'https://twitter.com/Tamiya667',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/ribbit_komei.jpg',
    'name'=>'shiryu',
    'role'=>'No.47',
    'twitter_url'=>'https://twitter.com/ribbit_komei',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/hotar_nazoneko.jpg',
    'name'=>'ほたる',
    'role'=>'No.50',
    'twitter_url'=>'https://twitter.com/hotar_nazoneko',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/Caliz00.jpg',
    'name'=>'Caliz',
    'role'=>'No.52',
    'twitter_url'=>'https://twitter.com/Caliz00',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/kokoan_.jpg',
    'name'=>'ymdあんぬ',
    'role'=>'No.57',
    'twitter_url'=>'https://twitter.com/kokoan_',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/ogutatosuto.jpg',
    'name'=>'倉下兎/Kosuto',
    'role'=>'No.58',
    'twitter_url'=>'https://twitter.com/ogutatosuto',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/kourin516.jpg',
    'name'=>'こうりん',
    'role'=>'No.62',
    'twitter_url'=>'https://twitter.com/kourin516',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/su_san4221.jpg',
    'name'=>'すーさん',
    'role'=>'No.64',
    'twitter_url'=>'https://twitter.com/su_san4221',
    'link_url'=>''
  ),
  array(
    'icon_path'=>'/images/member/icon/noname0nobody.jpg',
    'name'=>'えりえーる',
    'role'=>'No.65',
    'twitter_url'=>'https://twitter.com/noname0nobody',
    'link_url'=>''
  )
);

/*▼リスト テンプレートHTML
*************************************************************************************/
function listRendering($arrayName){
	$i = 1;
	foreach ($arrayName as $key => $value) {
    $icon = '/images/member/icon/default.jpg';
    if($value["icon_path"]){
      $icon = $value["icon_path"];
    }
    $twitter = '<span class="inner">Twitter</span>';
    if($value["twitter_url"]){
      $twitter = '<a href="'.$value["twitter_url"].'" target="_blank" class="inner">Twitter</a>';
    }
    $link = '<span class="inner">Link</span>';
    if($value["link_url"]){
      $link = '<a href="'.$value["link_url"].'" target="_blank" class="inner">Link</a>';
    }
    echo '
      <li>
        <div class="icon-wrap"><img src="'.$icon.'" alt=""></div>
        <h3 class="name">'.$value["name"].'</h3>
        <p class="role">'.$value["role"].'</p>
        <ul class="social-list">
          <li class="twitter">'.$twitter.'</li>
          <li class="link">'.$link.'</li>
        </ul>
      </li>
		';
	}
};
?>